title:            Avalon
description:      A jekyll Blog
url:              http://xhs.me/blog
paginate:         10

pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# Theme specific settings
theme:            b
signoff:          xi4oh4o
facebook_appid:   
google_analytics: 
disqus_shortname: xhs

base_path:        http://xhs.me/jekyll-wardrobe

owner:
  name:           Howe Isamu
  avatar:         'http://www.gravatar.com/avatar/fe0341da85d13073e94f92951b37d83d?size=200'

  bio:            "Hi,I'm Howe Isamu, aka xi4oh4o in elsewhere.
I live in ZhengZhou and like Programming and front-end design.
Nice to meet you!"

links_a: 
  - name:         Home
    url:          http://xhs.me/blog/
  - name:         Categories
    url:          http://xhs.me/blog/categories/
  - name:         Tags
    url:          http://xhs.me/blog/tags/
  - name:         Twitter
    url:          https://twitter.com/XHs
  - name:         Github
    url:          https://github.com/xi4oh4o
  - name:         Instagram
    url:          http://instagram.com/xi4oh4o
  - name:         About
    url:          http://xhs.me/blog/about/
  - name:         Feed
    url:          http://xhs.me/blog/atom.xml

links_b: 
  - name:         <span class="icon-home-2"></span>
    url:          http://xhs.me/blog/
  - name:         <span class="icon-drawer-2"></span>
    url:          http://xhs.me/blog/categories/
  - name:         <span class="icon-tags"></span>
    url:          http://xhs.me/blog/tags/
  - name:         <span class="icon-twitter"></span>
    url:          https://twitter.com/XHs
  - name:         <span class="icon-github-3"></span>
    url:          https://github.com/xi4oh4o
  - name:         <span class="icon-instagram"></span>
    url:          http://instagram.com/xi4oh4o
  - name:         <span class="icon-profile"></span>
    url:          http://xhs.me/blog/about/
  - name:         <span class="icon-feed"></span>
    url:          http://xhs.me/blog/atom.xml
